<?php

namespace Database\Seeders;

use App\Models\Agent;
use Illuminate\Database\Seeder;

class AgentSeeder extends Seeder
{
    public function run(): void
    {
        $agents = [
            [
                'slug'            => 'bid-tender',
                'name'            => 'Bid & Tender Response',
                'description'     => 'Automates government RFQ/RFT responses, selection criteria, and capability statements. Built for ICT consultancies, defence contractors, and government suppliers.',
                'badge'           => 'Popular',
                'rating'          => 4.90,
                'users_count'     => '340+',
                'price'           => '$499/mo',
                'category'        => 'Government & Procurement',
                'is_featured'     => false,
                'sort_order'      => 1,
                'checkout_name'   => 'Bid+Tender+Response',
                'target_audience' => 'ICT consultancies, Defence contractors, Government suppliers, Recruitment firms',
                'cta_headline'    => 'Win More Tenders with AI',
                'cta_sub'         => 'Start automating your government bid responses today',
                'features'        => ['Reads and parses RFQs', 'Matches CVs to selection criteria', 'Generates STAR method responses', 'Builds compliance matrices', 'Produces cover letters and executive summaries', 'Identifies gaps against requirements'],
                'includes'        => ['RFQ/RFT document analysis', 'CV-to-criteria matching', 'STAR response generation', 'Compliance matrix builder', 'Cover letters & executive summaries', 'Gap analysis against requirements'],
                'use_cases'       => [
                    ['title' => 'Government Procurement', 'description' => 'Respond to AusTender, panel arrangements, and RFT documents with AI-generated compliance matrices.'],
                    ['title' => 'CV Shortlisting',        'description' => 'Match consultant CVs to role requirements and generate capability statements automatically.'],
                    ['title' => 'Executive Summaries',    'description' => 'Produce polished cover letters and executive summaries tailored to selection criteria.'],
                ],
                'pricing_plans'   => [
                    ['name' => 'Starter',      'description' => 'For small teams',          'price' => '$299/month', 'amount' => 299,  'features' => ['Up to 5 responses/month', 'STAR generation', 'Email support'], 'is_recommended' => false, 'checkout_name' => 'Bid+Tender+Response+Starter'],
                    ['name' => 'Professional', 'description' => 'For growing consultancies', 'price' => '$499/month', 'amount' => 499,  'features' => ['Unlimited responses', 'CV matching', 'Compliance matrices', 'Priority support'], 'is_recommended' => true],
                    ['name' => 'Enterprise',   'description' => 'For large organisations',   'price' => 'Custom',     'amount' => null, 'features' => ['Dedicated instance', 'Custom integrations', 'SLA', 'White-label'], 'is_recommended' => false, 'contact_subject' => 'Bid+%26+Tender+Enterprise+Inquiry'],
                ],
                'faqs'            => [
                    ['question' => 'What procurement frameworks does it support?', 'answer' => 'AusTender, Commonwealth Grants Hub, state government portals, and custom frameworks. It reads any RFQ/RFT document format.'],
                    ['question' => 'Can it match multiple CVs?',                  'answer' => 'Yes. Upload a bench of consultant CVs and the agent matches the best fit to each selection criterion automatically.'],
                    ['question' => 'Is our tender data kept confidential?',       'answer' => 'All documents are processed in an isolated environment and never used to train models. Data is encrypted in transit and at rest.'],
                ],
            ],
            [
                'slug'            => 'security-compliance',
                'name'            => 'Security & IRAP Readiness',
                'description'     => 'Guides organisations through Essential Eight, ISM, PSPF, IRAP, ISO 27001, and cloud security readiness. Purpose-built for Australian government and regulated industries.',
                'badge'           => 'Premium',
                'rating'          => 4.95,
                'users_count'     => '180+',
                'price'           => '$799/mo',
                'category'        => 'Security & Compliance',
                'is_featured'     => true,
                'sort_order'      => 2,
                'checkout_name'   => 'Security+Compliance+IRAP',
                'target_audience' => 'SMEs entering government supply chains, SaaS companies, MSPs, Defence industry suppliers',
                'cta_headline'    => 'Accelerate Your Security Compliance',
                'cta_sub'         => 'Get IRAP-ready faster with AI-assisted compliance',
                'features'        => ['Gap analysis', 'Control mapping', 'Policy generation', 'Architecture reviews', 'Evidence collection guidance', 'Risk assessment summaries'],
                'includes'        => ['Essential Eight gap analysis', 'ISM / PSPF control mapping', 'Policy and procedure generation', 'Architecture review guidance', 'Evidence collection checklists', 'Risk assessment summaries'],
                'use_cases'       => [
                    ['title' => 'IRAP Readiness',   'description' => 'Assess your current security posture against ISM controls and generate an IRAP-ready evidence pack.'],
                    ['title' => 'Essential Eight',  'description' => 'Run a gap analysis across all eight mitigation strategies and produce remediation roadmaps with prioritised actions.'],
                    ['title' => 'Policy Generation','description' => 'Auto-generate security policies, procedures, and control statements aligned to PSPF and ISO 27001.'],
                ],
                'pricing_plans'   => [
                    ['name' => 'SME',          'description' => 'For small businesses',    'price' => '$499/month', 'amount' => 499,  'features' => ['Essential Eight gap analysis', 'Policy templates', 'Email support'], 'is_recommended' => false, 'checkout_name' => 'Security+Compliance+IRAP+SME'],
                    ['name' => 'Professional', 'description' => 'For regulated businesses', 'price' => '$799/month', 'amount' => 799,  'features' => ['Full ISM/PSPF mapping', 'Architecture reviews', 'Evidence pack', 'Priority support'], 'is_recommended' => true],
                    ['name' => 'Enterprise',   'description' => 'For large organisations',  'price' => 'Custom',     'amount' => null, 'features' => ['IRAP assessment support', 'Dedicated analyst', 'Custom framework mapping', 'SLA'], 'is_recommended' => false, 'contact_subject' => 'Security+Compliance+Enterprise+Inquiry'],
                ],
                'faqs'            => [
                    ['question' => 'Does this replace an IRAP assessor?',       'answer' => 'No — it prepares you for one. The agent generates evidence, gap reports, and remediation plans so your IRAP engagement is faster and cheaper.'],
                    ['question' => 'Which frameworks are supported?',           'answer' => 'Essential Eight, ISM, PSPF, ISO 27001, SOC 2, NIST CSF, and cloud security benchmarks (CIS, AWS, Azure, GCP).'],
                    ['question' => 'Can it analyse our existing architecture?', 'answer' => 'Yes. Upload diagrams, network maps, or descriptions and the agent produces security findings with control recommendations.'],
                ],
            ],
            [
                'slug'            => 'enterprise-architecture',
                'name'            => 'Enterprise Architecture',
                'description'     => 'Acts as a virtual enterprise and solution architect. Generates architecture options, decision records, integration patterns, and migration roadmaps for complex transformation programs.',
                'badge'           => 'Popular',
                'rating'          => 4.85,
                'users_count'     => '210+',
                'price'           => '$599/mo',
                'category'        => 'Architecture & Strategy',
                'is_featured'     => false,
                'sort_order'      => 3,
                'checkout_name'   => 'Enterprise+Architecture',
                'target_audience' => 'CIO offices, Digital transformation programs, ERP and cloud migration projects, Government ICT programs',
                'cta_headline'    => 'Build Better Architecture Faster',
                'cta_sub'         => 'Reduce your architecture documentation burden with AI',
                'features'        => ['Architecture options', 'Target-state models', 'Integration patterns', 'ADR generation', 'Capability mapping', 'Migration roadmaps'],
                'includes'        => ['Architecture options analysis', 'Target-state model generation', 'Integration pattern documentation', 'Architecture decision records (ADRs)', 'Business capability mapping', 'Migration roadmap generation'],
                'use_cases'       => [
                    ['title' => 'Target State Design', 'description' => 'Define your future-state architecture across application, data, infrastructure, and security domains.'],
                    ['title' => 'Decision Records',    'description' => 'Generate Architecture Decision Records (ADRs) that document options considered, rationale, and trade-offs.'],
                    ['title' => 'Migration Roadmaps',  'description' => 'Produce phased migration plans with dependencies, risks, and business capability alignment.'],
                ],
                'pricing_plans'   => [
                    ['name' => 'Starter',      'description' => 'For project teams',            'price' => '$349/month', 'amount' => 349,  'features' => ['ADR generation', 'Architecture options', 'Email support'], 'is_recommended' => false, 'checkout_name' => 'Enterprise+Architecture+Starter'],
                    ['name' => 'Professional', 'description' => 'For transformation programs',   'price' => '$599/month', 'amount' => 599,  'features' => ['Full target-state modelling', 'Integration patterns', 'Roadmaps', 'Priority support'], 'is_recommended' => true],
                    ['name' => 'Enterprise',   'description' => 'For program-level architecture','price' => 'Custom',     'amount' => null, 'features' => ['Program-level architecture', 'Custom frameworks (TOGAF, SABSA)', 'Dedicated architect', 'SLA'], 'is_recommended' => false, 'contact_subject' => 'Enterprise+Architecture+Enterprise+Inquiry'],
                ],
                'faqs'            => [
                    ['question' => 'Does it follow TOGAF or other frameworks?',     'answer' => 'Yes. The agent can align outputs to TOGAF, SABSA, and DTA frameworks, or operate framework-agnostic to suit your program.'],
                    ['question' => 'Can it work with our existing documentation?',  'answer' => 'Upload existing architecture diagrams, system lists, or strategy documents and the agent builds on them rather than starting from scratch.'],
                    ['question' => 'Is it suitable for government ICT programs?',   'answer' => 'Absolutely. It is optimised for the documentation burden in government and regulated environments, producing audit-ready artefacts.'],
                ],
            ],
            [
                'slug'            => 'digital-avatar',
                'name'            => 'Digital Avatar & Executive Clone',
                'description'     => 'Creates AI-powered professional avatars for executives, consultants, trainers, and public-facing staff. Enterprise-grade, secure, and multilingual.',
                'badge'           => 'New',
                'rating'          => 4.90,
                'users_count'     => '520+',
                'price'           => '$800',
                'category'        => 'Communications & Avatar',
                'is_featured'     => false,
                'sort_order'      => 4,
                'checkout_name'   => 'Digital+Avatar',
                'target_audience' => 'Consultants and professional services firms, Corporate trainers, Influencers and content creators, Government communications teams',
                'tagline'         => 'Professional-grade secure avatars for enterprise and government',
                'cta_headline'    => 'Scale Your Presence with AI',
                'cta_sub'         => 'Deploy professional avatars for enterprise and government',
                'features'        => ['Talking avatar generation', 'Voice cloning', 'FAQ handling', 'Sales/demo presentations', 'Training delivery', 'Multilingual delivery'],
                'includes'        => ['Talking avatar generation', 'Voice cloning (licensed)', 'FAQ and Q&A handling', 'Sales and demo presentations', 'Training content delivery', 'Multilingual output'],
                'use_cases'       => [
                    ['title' => 'Executive Communications', 'description' => 'Scale your executive presence with AI avatars that deliver consistent messages across channels without scheduling constraints.'],
                    ['title' => 'Training Delivery',        'description' => 'Convert PowerPoint decks and scripts into talking-head training videos in minutes. Supports multilingual delivery.'],
                    ['title' => 'Sales Presentations',      'description' => 'Create personalised demo videos for prospects at scale, customised by industry and use case.'],
                ],
                'pricing_plans'   => [
                    ['name' => 'Starter',      'description' => 'For individuals',          'price' => '$149/month', 'amount' => 149,  'features' => ['10 avatar videos/month', 'Single voice', 'Email support'], 'is_recommended' => false, 'checkout_name' => 'Digital+Avatar+Starter'],
                    ['name' => 'Professional', 'description' => 'For teams and businesses', 'price' => '$800',       'amount' => 800,  'features' => ['50 videos/month', 'Voice cloning', 'Multilingual', 'Priority support'], 'is_recommended' => true],
                    ['name' => 'Enterprise',   'description' => 'For large organisations',  'price' => 'Custom',     'amount' => null, 'features' => ['Unlimited videos', 'Custom avatar build', 'Secure hosting', 'SLA'], 'is_recommended' => false, 'contact_subject' => 'Digital%20Avatar%20Enterprise%20Inquiry'],
                ],
                'faqs'            => [
                    ['question' => 'How realistic is the avatar?',         'answer' => 'Avatars are indistinguishable from recorded video in most contexts. You can use your own likeness or choose from a library of professional presenters.'],
                    ['question' => 'Is voice cloning legal and ethical?',  'answer' => 'Yes — all voice cloning requires explicit consent from the voice owner. We provide a consent and licensing workflow as part of onboarding.'],
                    ['question' => 'Can it handle live Q&A?',              'answer' => 'The agent can be configured to answer pre-defined FAQs in real time via a chat-backed avatar interface.'],
                ],
            ],
            [
                'slug'            => 'knowledge-management',
                'name'            => 'Knowledge Management & SOP',
                'description'     => 'Turns scattered organisational knowledge into searchable operational intelligence. Converts PDFs, wikis, and documents into SOPs, onboarding material, and instant answers.',
                'badge'           => 'Popular',
                'rating'          => 4.80,
                'users_count'     => '290+',
                'price'           => '$399/mo',
                'category'        => 'Knowledge Management',
                'is_featured'     => false,
                'sort_order'      => 5,
                'checkout_name'   => 'Knowledge+Management+SOP',
                'target_audience' => 'Government departments, MSPs and service desks, Operations teams, HR and onboarding teams',
                'cta_headline'    => 'Stop Losing Institutional Knowledge',
                'cta_sub'         => 'Turn your documents into operational intelligence',
                'features'        => ['Document-to-knowledge conversion', 'SOP generation', 'Policy Q&A', 'Onboarding content', 'SharePoint/Confluence integration', 'Gap identification'],
                'includes'        => ['PDF, wiki, and document ingestion', 'Automatic SOP generation', 'Internal policy Q&A', 'Onboarding material creation', 'SharePoint & Confluence integration', 'Knowledge gap identification'],
                'use_cases'       => [
                    ['title' => 'SOP Generation',  'description' => 'Upload process documentation and the agent produces structured, version-controlled Standard Operating Procedures automatically.'],
                    ['title' => 'Internal Q&A',    'description' => 'Staff ask questions in plain language and receive instant, cited answers drawn from your internal knowledge base.'],
                    ['title' => 'Onboarding Packs','description' => 'Generate role-specific onboarding material from existing documentation in minutes, not weeks.'],
                ],
                'pricing_plans'   => [
                    ['name' => 'Starter',      'description' => 'For small teams',          'price' => '$199/month', 'amount' => 199,  'features' => ['Up to 50 documents', 'SOP generation', 'Email support'], 'is_recommended' => false, 'checkout_name' => 'Knowledge+Management+SOP+Starter'],
                    ['name' => 'Professional', 'description' => 'For growing organisations', 'price' => '$399/month', 'amount' => 399,  'features' => ['Unlimited documents', 'SharePoint/Confluence integration', 'Q&A interface', 'Priority support'], 'is_recommended' => true],
                    ['name' => 'Enterprise',   'description' => 'For large organisations',   'price' => 'Custom',     'amount' => null, 'features' => ['Dedicated instance', 'Custom integrations', 'Audit logging', 'SLA'], 'is_recommended' => false, 'contact_subject' => 'Knowledge+Management+Enterprise+Inquiry'],
                ],
                'faqs'            => [
                    ['question' => 'What document formats does it support?',          'answer' => 'PDF, Word, Excel, PowerPoint, Markdown, HTML, SharePoint pages, Confluence spaces, and plain text.'],
                    ['question' => 'How does the Q&A stay accurate?',                 'answer' => 'Answers are grounded in your uploaded documents with citations. The agent does not hallucinate — if the answer isn\'t in the knowledge base, it says so.'],
                    ['question' => 'Can it stay up to date as documents change?',     'answer' => 'Yes. Connect it to your SharePoint or Confluence and it re-indexes on document change events automatically.'],
                ],
            ],
            [
                'slug'            => 'cyber-incident',
                'name'            => 'Cyber Incident & Threat Intel',
                'description'     => 'Acts as a first-line cyber operations assistant for SOC teams, MSPs, and security consultancies. Summarises logs, correlates threat intel, triages incidents, and drafts executive reports.',
                'badge'           => 'Premium',
                'rating'          => 4.90,
                'users_count'     => '150+',
                'price'           => '$699/mo',
                'category'        => 'Cyber Operations',
                'is_featured'     => true,
                'sort_order'      => 6,
                'checkout_name'   => 'Cyber+Incident+Threat+Intel',
                'target_audience' => 'SOC teams and analysts, MSPs with security offerings, Small government agencies, Security consultancies',
                'tagline'         => 'SIEM integrations (Sentinel, Defender, Splunk, CrowdStrike) coming soon.',
                'cta_headline'    => 'Respond Faster. Report Clearer.',
                'cta_sub'         => 'AI-powered cyber operations for security teams',
                'features'        => ['Log summarisation', 'Threat intel correlation', 'Incident triage', 'IOC extraction', 'Executive reports', 'Playbook recommendations'],
                'includes'        => ['Log summarisation and analysis', 'Threat intelligence correlation', 'Incident triage and classification', 'IOC extraction', 'Executive incident reports', 'Playbook recommendations'],
                'use_cases'       => [
                    ['title' => 'Incident Triage',        'description' => 'Feed in raw logs or alert data and receive a structured triage report with severity classification, affected assets, and recommended containment actions.'],
                    ['title' => 'Threat Intel Correlation','description' => 'Cross-reference IOCs against threat feeds and produce enriched intelligence summaries for analysts.'],
                    ['title' => 'Executive Reporting',    'description' => 'Automatically draft non-technical executive incident reports from technical findings, ready to brief leadership within minutes.'],
                ],
                'pricing_plans'   => [
                    ['name' => 'SME',          'description' => 'For small security teams', 'price' => '$399/month', 'amount' => 399,  'features' => ['Incident triage', 'IOC extraction', 'Executive reports', 'Email support'], 'is_recommended' => false, 'checkout_name' => 'Cyber+Incident+Threat+Intel+SME'],
                    ['name' => 'Professional', 'description' => 'For SOC teams and MSPs',   'price' => '$699/month', 'amount' => 699,  'features' => ['Full threat intel correlation', 'Log analysis', 'Playbooks', 'Priority support'], 'is_recommended' => true],
                    ['name' => 'Enterprise',   'description' => 'For large organisations',  'price' => 'Custom',     'amount' => null, 'features' => ['SIEM integration', 'Dedicated instance', 'Custom playbooks', 'SLA'], 'is_recommended' => false, 'contact_subject' => 'Cyber+Incident+Enterprise+Inquiry'],
                ],
                'faqs'            => [
                    ['question' => 'Does it connect to our SIEM?',                'answer' => 'SIEM integrations (Sentinel, Splunk, Defender, CrowdStrike) are on the roadmap. Currently, paste or upload log excerpts and alert data directly.'],
                    ['question' => 'How does it handle sensitive incident data?', 'answer' => 'All data is processed in an isolated environment. Nothing is retained after the session. Suitable for protected and sensitive incident data.'],
                    ['question' => 'Can it generate playbooks from scratch?',     'answer' => 'Yes. Describe the incident type and environment and the agent generates a structured playbook with detection, containment, eradication, and recovery steps.'],
                ],
            ],
            [
                'slug'            => 'content-creator',
                'name'            => 'Content Creator',
                'description'     => 'Autonomous content generation for blogs, social media, and marketing campaigns. Powered by advanced language models.',
                'badge'           => 'Popular',
                'rating'          => 4.90,
                'users_count'     => '1,250+',
                'price'           => '$29/mo',
                'category'        => 'Content & Marketing',
                'is_featured'     => false,
                'sort_order'      => 7,
                'checkout_name'   => 'Content+Creator',
                'target_audience' => 'Content creators, marketers, and agencies worldwide',
                'cta_headline'    => 'Ready to Transform Your Content?',
                'cta_sub'         => 'Start creating with AI today',
                'features'        => ['Multi-format Generation', 'SEO Optimization', 'Brand Voice Learning', 'Tone & Style Control', 'Plagiarism Detection', 'Real-time Collaboration', 'API Integration', 'Analytics Dashboard'],
                'includes'        => ['50 content pieces/month', 'Multiple content formats (blog, social, email)', 'AI-powered SEO optimization', 'Brand voice customization', '24/7 customer support'],
                'use_cases'       => [
                    ['title' => 'Blog Content',    'description' => 'Generate high-quality blog posts with SEO optimization and topic research.'],
                    ['title' => 'Social Media',    'description' => 'Create engaging posts for Twitter, LinkedIn, Instagram, and more.'],
                    ['title' => 'Email Campaigns', 'description' => 'Write compelling newsletters and marketing emails that convert.'],
                ],
                'pricing_plans'   => [
                    ['name' => 'Starter',      'description' => 'For individuals',     'price' => '$29/month',  'amount' => 29,   'features' => ['50 content pieces', 'Basic customization', 'Email support'], 'is_recommended' => false, 'checkout_name' => 'Content+Creator+Starter'],
                    ['name' => 'Professional', 'description' => 'For content teams',   'price' => '$79/month',  'amount' => 79,   'features' => ['200 content pieces', 'Advanced customization', 'Priority support', 'Team collaboration'], 'is_recommended' => true, 'checkout_name' => 'Content+Creator+Pro'],
                    ['name' => 'Enterprise',   'description' => 'For large organizations','price' => 'Custom',  'amount' => null, 'features' => ['Unlimited content', 'Custom integrations', 'Dedicated support', 'SLA guarantee'], 'is_recommended' => false, 'contact_subject' => 'Enterprise+Plan+Inquiry'],
                ],
                'faqs'            => [
                    ['question' => 'Can I cancel my subscription anytime?',   'answer' => "Yes, you can cancel your subscription at any time. No questions asked. You'll have access until the end of your billing cycle."],
                    ['question' => 'Can I upgrade or downgrade my plan?',     'answer' => 'Absolutely! You can change your plan at any time. Upgrades are prorated, and downgrades take effect at the start of your next billing cycle.'],
                ],
            ],
            [
                'slug'            => 'support-bot',
                'name'            => 'Customer Support Bot',
                'description'     => '24/7 intelligent customer support with natural language understanding. Resolve issues faster and improve customer satisfaction.',
                'badge'           => 'New',
                'rating'          => 4.80,
                'users_count'     => '890+',
                'price'           => '$49/mo',
                'category'        => 'Customer Support',
                'is_featured'     => false,
                'sort_order'      => 8,
                'checkout_name'   => 'Customer+Support+Bot',
                'target_audience' => '890+ companies handling over 10 million customer interactions monthly',
                'cta_headline'    => 'Improve Customer Support Today',
                'cta_sub'         => 'Reduce response times and increase satisfaction',
                'features'        => ['Natural Language Processing', 'Multi-Channel Support', 'Sentiment Detection', 'Human Handoff', 'Knowledge Base Integration', 'Conversation History', 'Issue Classification', 'Performance Analytics'],
                'includes'        => ['Unlimited conversations', 'Multi-language support', 'Integration with ticketing systems', 'Sentiment analysis', '24/7 monitoring'],
                'use_cases'       => [
                    ['title' => 'Chat Support',         'description' => 'Instant responses to customer inquiries on web and mobile.'],
                    ['title' => 'Helpdesk Integration', 'description' => 'Seamless integration with your existing helpdesk platform.'],
                    ['title' => 'Lead Qualification',   'description' => 'Qualify leads and route them to the right sales teams.'],
                ],
                'pricing_plans'   => [
                    ['name' => 'Starter',      'description' => 'For small businesses',    'price' => '$29/month', 'amount' => 29,   'features' => ['1,000 conversations/month', 'Email support', 'Basic analytics'], 'is_recommended' => false, 'checkout_name' => 'Support+Bot+Starter'],
                    ['name' => 'Professional', 'description' => 'For growing teams',       'price' => '$49/month', 'amount' => 49,   'features' => ['Unlimited conversations', 'Priority support', 'Advanced analytics', 'Integrations'], 'is_recommended' => true],
                    ['name' => 'Enterprise',   'description' => 'For large organizations', 'price' => 'Custom',    'amount' => null, 'features' => ['Custom volume', 'Custom integrations', 'Dedicated support', 'SLA guarantee'], 'is_recommended' => false, 'contact_subject' => 'Support+Bot+Enterprise+Inquiry'],
                ],
                'faqs'            => [
                    ['question' => 'How long does setup take?',           'answer' => 'Setup typically takes 30 minutes. You can customize the bot to match your brand and connect it to your existing systems.'],
                    ['question' => 'Can it handle complex issues?',       'answer' => 'Yes, our bot can handle complex conversations and automatically escalates to human agents when needed.'],
                    ['question' => 'What languages are supported?',       'answer' => 'We support 50+ languages. The bot can even detect and switch between languages in the same conversation.'],
                ],
            ],
            [
                'slug'            => 'data-analyzer',
                'name'            => 'Data Analyzer Pro',
                'description'     => 'Advanced data analysis, visualization, and insights generation from any dataset. Uncover patterns and make data-driven decisions.',
                'badge'           => 'Premium',
                'rating'          => 4.95,
                'users_count'     => '2,100+',
                'price'           => '$79/mo',
                'category'        => 'Data & Analytics',
                'is_featured'     => true,
                'sort_order'      => 9,
                'checkout_name'   => 'Data+Analyzer+Pro',
                'target_audience' => 'Data analysts, business intelligence teams, and enterprises worldwide',
                'cta_headline'    => 'Start Analyzing Data Like Never Before',
                'cta_sub'         => 'Unlock insights with advanced AI-powered analytics',
                'features'        => ['Statistical Analysis', 'Data Visualization', 'Trend Detection', 'Anomaly Detection', 'Predictive Modeling', 'Report Generation', 'Multi-format Import', 'Real-time Dashboards'],
                'includes'        => ['Unlimited data analysis', 'Advanced visualization tools', 'Predictive analytics', 'Real-time alerts', 'Premium support'],
                'use_cases'       => [
                    ['title' => 'Business Intelligence', 'description' => 'Analyze business metrics and identify growth opportunities.'],
                    ['title' => 'Financial Analysis',    'description' => 'Track financial trends and forecast future performance.'],
                    ['title' => 'Research & Insights',   'description' => 'Deep dive analysis and comprehensive research reports.'],
                ],
                'pricing_plans'   => [
                    ['name' => 'Basic',        'description' => 'For analysts',            'price' => '$49/month',  'amount' => 49,   'features' => ['100 MB storage', 'Basic analysis', 'Email support'], 'is_recommended' => false, 'checkout_name' => 'Data+Analyzer+Basic'],
                    ['name' => 'Professional', 'description' => 'For teams',               'price' => '$79/month',  'amount' => 79,   'features' => ['1 GB storage', 'Advanced analytics', 'Priority support', 'Team collaboration'], 'is_recommended' => true],
                    ['name' => 'Enterprise',   'description' => 'For large organizations', 'price' => 'Custom',     'amount' => null, 'features' => ['Unlimited storage', 'Custom integrations', 'Dedicated support', 'White-label options'], 'is_recommended' => false, 'contact_subject' => 'Data+Analyzer+Enterprise+Inquiry'],
                ],
                'faqs'            => [
                    ['question' => 'What data formats are supported?', 'answer' => 'We support CSV, Excel, JSON, SQL databases, and many more formats. You can even import directly from APIs.'],
                    ['question' => 'Is my data secure?',               'answer' => 'Yes, all data is encrypted in transit and at rest. We comply with GDPR, HIPAA, and SOC 2 standards.'],
                    ['question' => 'Can I export my reports?',         'answer' => 'Absolutely! Export as PDF, PNG, SVG, or interactive HTML. Share reports directly with your team.'],
                ],
            ],
        ];

        foreach ($agents as $data) {
            Agent::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
