<?php

namespace Database\Seeders;

use App\Models\Training;
use Illuminate\Database\Seeder;

class TrainingSeeder extends Seeder
{
    public function run(): void
    {
        $trainings = [
            [
                'slug'             => 'introduction-to-ai',
                'title'            => 'Introduction to AI',
                'description'      => 'A full day, hands-on workshop covering the 5 top AI tools for personal efficiency. Work through real exercises with each tool, leave with skills you can apply immediately — and revisit everything with lifetime video access after the course.',
                'category'         => 'Fundamentals',
                'format'           => 'Workshop',
                'duration'         => 'Full Day (8 hrs)',
                'level'            => 'All levels',
                'modules_count'    => 5,
                'price'            => '$1,500',
                'price_unit'       => 'per person',
                'badge'            => 'Popular',
                'topics'           => [
                    'ChatGPT — writing, research & idea generation',
                    'Claude — analysis, summarisation & long-form work',
                    'HeyGen — AI video avatars & personalised video at scale',
                    'NotebookLM — AI-powered research, notes & source analysis',
                    'Hermes Agent — autonomous AI agent for personal task automation',
                ],
                'includes'         => [
                    'Full day live hands-on workshop',
                    'Lifetime video replay access',
                    'Course materials & templates',
                    'Certificate of completion',
                ],
                'instructor'       => 'ApiSpi Team',
                'instructor_role'  => 'AI Productivity & Tools',
                'checkout_name'    => 'Introduction+to+AI+Course',
                'checkout_amount'  => 1500,
                'is_active'        => true,
                'is_featured'      => true,
                'sort_order'       => 10,
                'cta_headline'     => 'Start Using AI Today',
                'cta_sub'          => 'One day. Five tools. Real skills you can apply immediately.',
            ],
            [
                'slug'             => 'digital-avatar',
                'title'            => 'Digital Avatar',
                'description'      => 'Create lifelike AI-powered digital avatars for business, content creation, and customer engagement. Learn to build, train, and deploy your own avatar from scratch.',
                'category'         => 'Creative AI',
                'format'           => 'Online',
                'duration'         => '6 hours',
                'level'            => 'Beginner–Intermediate',
                'modules_count'    => 8,
                'price'            => '$250',
                'price_unit'       => 'per avatar',
                'badge'            => 'New',
                'topics'           => [
                    'What are digital avatars & real-world use cases',
                    'Choosing the right AI models (image, voice, video)',
                    'Building a custom avatar with generative AI',
                    'Lip-sync, animation & real-time rendering',
                    'Integrating your avatar into web & mobile apps',
                    'Monetising digital avatar products',
                ],
                'includes'         => [
                    '6 hours of on-demand video',
                    'Step-by-step build guide',
                    'Access to recommended tools & free tiers',
                    'Certificate of completion',
                ],
                'instructor'       => 'ApiSpi Team',
                'instructor_role'  => 'AI & Creative Technology',
                'checkout_name'    => 'Digital+Avatar+Course',
                'checkout_amount'  => 250,
                'is_active'        => true,
                'is_featured'      => false,
                'sort_order'       => 20,
                'cta_headline'     => 'Build Your Digital Avatar',
                'cta_sub'          => 'Deploy your AI presence — videos, demos, and social content at scale.',
            ],
            [
                'slug'             => 'prompt-engineering-masterclass',
                'title'            => 'Prompt Engineering Masterclass',
                'description'      => 'Go beyond basic prompts. Learn structured prompting frameworks, chain-of-thought techniques, and how to build reliable AI workflows that consistently deliver production-quality results.',
                'category'         => 'Technical',
                'format'           => 'Workshop',
                'duration'         => '1 day (7 hrs)',
                'level'            => 'Intermediate',
                'modules_count'    => 6,
                'price'            => '$750',
                'price_unit'       => 'per person',
                'badge'            => null,
                'topics'           => [
                    'Anatomy of an effective prompt — structure, context, constraints',
                    'Chain-of-thought and step-by-step reasoning techniques',
                    'System prompts, personas & role-based instructions',
                    'Few-shot and zero-shot prompting patterns',
                    'Prompt templates for business workflows',
                    'Evaluating and iterating on prompt quality',
                ],
                'includes'         => [
                    'Full day workshop with exercises',
                    'Prompt template library (50+ templates)',
                    'Evaluation rubric & testing framework',
                    'Certificate of completion',
                ],
                'instructor'       => 'ApiSpi Team',
                'instructor_role'  => 'AI Engineering',
                'checkout_name'    => 'Prompt+Engineering+Masterclass',
                'checkout_amount'  => 750,
                'is_active'        => true,
                'is_featured'      => false,
                'sort_order'       => 30,
                'cta_headline'     => 'Master the Language of AI',
                'cta_sub'          => 'The skill that multiplies the value of every AI tool you use.',
            ],
            [
                'slug'             => 'ai-for-business-leaders',
                'title'            => 'AI for Business Leaders',
                'description'      => 'A strategic half-day workshop designed for executives and managers. Understand AI capabilities, identify automation opportunities, evaluate ROI, and lead AI adoption across your organisation without writing a single line of code.',
                'category'         => 'Leadership',
                'format'           => 'Workshop',
                'duration'         => 'Half Day (4 hrs)',
                'level'            => 'All levels',
                'modules_count'    => 4,
                'price'            => '$995',
                'price_unit'       => 'per person',
                'badge'            => null,
                'topics'           => [
                    'The current AI landscape — what\'s real, what\'s hype',
                    'Identifying high-value automation opportunities in your business',
                    'Building the business case: ROI frameworks for AI projects',
                    'Change management & staff adoption strategies',
                ],
                'includes'         => [
                    'Half day facilitated workshop',
                    'AI opportunity assessment worksheet',
                    'ROI calculator template',
                    'Certificate of completion',
                ],
                'instructor'       => 'ApiSpi Team',
                'instructor_role'  => 'AI Strategy & Transformation',
                'checkout_name'    => 'AI+for+Business+Leaders',
                'checkout_amount'  => 995,
                'is_active'        => true,
                'is_featured'      => false,
                'sort_order'       => 40,
                'cta_headline'     => 'Lead Your AI Transformation',
                'cta_sub'          => 'Strategic clarity for leaders who need to act, not just understand.',
            ],
            [
                'slug'             => 'building-ai-agents-with-apis',
                'title'            => 'Building AI Agents with APIs',
                'description'      => 'A hands-on technical course for developers and technical professionals. Build autonomous AI agents that connect to real-world APIs, handle multi-step tasks, and run production workflows using Claude, OpenAI, and tool-use patterns.',
                'category'         => 'Technical',
                'format'           => 'Online',
                'duration'         => '3 days (12 hrs)',
                'level'            => 'Intermediate–Advanced',
                'modules_count'    => 10,
                'price'            => '$1,200',
                'price_unit'       => 'per person',
                'badge'            => null,
                'topics'           => [
                    'Agentic AI architecture — tools, memory, planning loops',
                    'Claude & OpenAI API deep dive — tool use and function calling',
                    'Building your first autonomous agent from scratch',
                    'Connecting agents to external APIs (REST, webhooks, databases)',
                    'Multi-step task orchestration and error handling',
                    'Agent memory: short-term, long-term and retrieval patterns',
                    'Human-in-the-loop and approval workflows',
                    'Testing, monitoring and deploying agents to production',
                ],
                'includes'         => [
                    '3 days of guided instruction',
                    'Full source code for all course agents',
                    'Private GitHub repo with templates',
                    'Certificate of completion',
                ],
                'instructor'       => 'ApiSpi Team',
                'instructor_role'  => 'AI Engineering & Agent Development',
                'checkout_name'    => 'Building+AI+Agents+with+APIs',
                'checkout_amount'  => 1200,
                'is_active'        => true,
                'is_featured'      => false,
                'sort_order'       => 50,
                'cta_headline'     => 'Build Agents That Actually Work',
                'cta_sub'          => 'From your first API call to a production-ready autonomous agent.',
            ],
            [
                'slug'             => 'enterprise-ai-strategy',
                'title'            => 'Enterprise AI Strategy',
                'description'      => 'A comprehensive 2-day workshop for senior teams ready to implement AI at scale. Covers AI governance, security, vendor evaluation, pilot program design, and building an internal AI capability that compounds over time.',
                'category'         => 'Leadership',
                'format'           => 'Workshop',
                'duration'         => '2 days (14 hrs)',
                'level'            => 'Advanced',
                'modules_count'    => 8,
                'price'            => '$2,500',
                'price_unit'       => 'per person',
                'badge'            => 'Certification',
                'topics'           => [
                    'Enterprise AI maturity model — where are you now?',
                    'AI governance frameworks and responsible use policies',
                    'Security, data privacy and compliance considerations',
                    'Vendor evaluation — build vs buy vs integrate',
                    'Designing and running AI pilot programs',
                    'Measuring impact: KPIs and success metrics for AI projects',
                    'Building internal AI capability and upskilling teams',
                    'Creating a 12-month AI adoption roadmap',
                ],
                'includes'         => [
                    '2-day intensive workshop',
                    'AI governance policy template pack',
                    'Vendor evaluation scorecard',
                    'AI adoption roadmap canvas',
                    'Certificate of completion',
                ],
                'instructor'       => 'ApiSpi Team',
                'instructor_role'  => 'AI Strategy & Enterprise Architecture',
                'checkout_name'    => 'Enterprise+AI+Strategy',
                'checkout_amount'  => 2500,
                'is_active'        => true,
                'is_featured'      => false,
                'sort_order'       => 60,
                'cta_headline'     => 'Build an AI-Ready Enterprise',
                'cta_sub'          => 'Strategy, governance and execution — done right from the start.',
            ],
        ];

        foreach ($trainings as $data) {
            Training::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
